[package]
name = "rust-c8"
version = "0.1.0"
authors = ["Evance Soumaoro <evanxg852000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.32.0"
rand = "0.7.0"