#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define SCREEN_WIDTH 768
#define SCREEN_HEIGHT 1024

#define SPLASH_STATE_SHOW_TIME 3.0

#define PIPE_MOVEMENT_SPEED 200.0f

#define PIPE_SPAWN_FREQUENCY 1.7f

#define BIRD_ANIMATION_DURATION 0.4f

#define GRAVITY 350.0f
#define FLYING_SPEED 350.0f
#define FLYING_DURATION 0.25f

#define ROTATION_SPEED 100.0f

#define FLASH_SPEED 1500.0f

#define TIME_BEFORE_GAME_OVER_APEARS 1.5f

#define BRONZE_MEDAL_SCORE 0
#define SILVER_MEDAL_SCORE 5 
#define GOLD_MEDAL_SCORE 25 
#define PLATINUM_MEDAL_SCORE 100 

#endif