[package]
name = "lsmdb"
version = "0.1.0"
authors = ["Evance Soumaoro <evanxg852000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "1.8.1"
byteorder = "1.3.4"
serde = "1.0.104"